<a href="https://colab.research.google.com/github/Nil1205/statistic/blob/main/Statistics_Assignment_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Descriptive Statistics

 Import **NumPy**, **SciPy**, and **Pandas**

In [2]:
import numpy as np
import pandas as pd
from scipy import stats

 Randomly generate 1,000 samples from the normal distribution using `np.random.normal()`(mean = 100, standard deviation = 15)

In [3]:
samples = np.random.normal(100,15,1000)
samples

array([106.07831492, 123.02111637,  69.16371634, 102.42097761,
       108.90914923, 111.64214111, 114.04485469,  73.95411864,
        85.71396724, 131.10171801, 113.65507284,  85.30801529,
       133.92133389, 134.93312929,  98.64490049, 119.46766633,
        90.52468146,  98.52937627,  83.7241481 , 128.16251935,
        90.5294224 ,  97.94242285,  84.70978825,  84.8373157 ,
        95.65305079,  80.42432323, 136.81378818,  87.01098778,
        98.26880797, 117.42806413, 105.62821742, 108.93616696,
        90.88246638, 121.53243331,  96.20546675,  99.29407473,
        86.4271618 , 105.86928486,  94.11287932,  99.44637195,
       115.48427178, 121.28070018,  77.78573185, 104.64083376,
        96.33828541, 119.02813073, 117.80522119,  77.70268244,
       111.39815129, 133.16249106,  86.59875618,  66.29782138,
        95.60597327, 109.63965656,  93.98239208,  86.98879964,
        63.3325423 , 102.48505335,  83.41005163,  92.86370689,
        72.60142775,  87.74689502, 118.35664034, 120.44

Compute the **mean**, **median**, and **mode**

In [15]:
mean =round(np.mean(samples),3)
median =round(np.median(samples),3)
mode =stats.mode(samples)
print("mean is {}, median is {} and mode is {}.".format(mean, median, mode))

mean is 100.013, median is 99.066 and mode is ModeResult(mode=array([57.01354744]), count=array([1])).


Compute the **min**, **max**, **Q1**, **Q3**, and **interquartile range**

In [18]:
min = round(np.min(samples),2)
max =round(np.max(samples),2)
q1 =round(np.percentile(samples, 25),2)
q3 =round(np.percentile(samples, 75),2)
iqr =round(stats.iqr(samples),2)
iqr2=round((q3-q1),2)
print("min= ", min)
print("max= ", max)
print("q1= ", q1)
print("q3= ", q3)
print("iqr: {} and iqr2: {} are equal.".format(iqr,iqr2))

min=  57.01
max=  155.12
q1=  89.82
q3=  109.53
iqr: 19.71 and iqr2: 19.71 are equal.


Compute the **variance** and **standard deviation**

In [22]:
variance = round(np.var(samples),3)
std_dev =round(np.std(samples),3)
print("variance= {}, std_dev= {} ".format(variance, std_dev))

variance= 215.371, std_dev= 14.676 


Compute the **skewness** and **kurtosis**

In [23]:
skewness =round(stats.skew(samples),3)
kurtosis =round(stats.kurtosis(samples),3)
print("skewness= {}, kurtosis= {}".format(skewness, kurtosis))

skewness= 0.167, kurtosis= 0.032


## NumPy Correlation Calculation

Create an array x of integers between 10 (inclusive) and 20 (exclusive). Use `np.arange()`

In [24]:
x = np.arange(10,20)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

Then use `np.array()` to create a second array y containing 10 arbitrary integers.

In [26]:

y=np.array([13,6,7,34,47,23,56,34,5,1])
y

array([13,  6,  7, 34, 47, 23, 56, 34,  5,  1])

Once you have two arrays of the same length, you can compute the **correlation coefficient** between x and y

In [27]:
r = np.corrcoef(x,y)
r

array([[1.        , 0.05889366],
       [0.05889366, 1.        ]])

## Pandas Correlation Calculation

Run the code below

In [28]:
x = pd.Series(range(10, 20))
y = pd.Series([2, 1, 4, 5, 8, 12, 18, 25, 96, 48])

Call the relevant method  to calculate Pearson's r correlation.

In [31]:
r =stats.pearsonr(x,y)
r

(0.758640289091187, 0.010964341301680813)

In [32]:
r = x.corr(y)
r= y.corr(x)
r

0.7586402890911869

OPTIONAL. Call the relevant method to calculate Spearman's rho correlation.

In [35]:
rho =x.corr(y, method='spearman')
rho

0.9757575757575757

## Seaborn Dataset Tips

Import Seaborn Library

In [36]:
import seaborn as sns

Load "tips" dataset from Seaborn

In [37]:
tips = sns.load_dataset("tips")

Generate descriptive statistics include those that summarize the central tendency, dispersion

In [38]:
tips.describe()

total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

Call the relevant method to calculate pairwise Pearson's r correlation of columns

In [41]:
tips.corr('pearson')

total_bill       tip      size
total_bill    1.000000  0.675734  0.598315
tip           0.675734  1.000000  0.489299
size          0.598315  0.489299  1.000000